// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTransition: typeof import('./../src/components/router-transition/router-transition.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    XDialog: typeof import('./../src/components/XDialog/index.vue')['default']
  }
}
